@WebApplication1_HostAddress = http://localhost:5090

GET {{WebApplication1_HostAddress}}/weatherforecast/
Accept: application/json

###

# GET {{WebApplication1_HostAddress}}/

GET {{WebApplication1_HostAddress}}/api/ErrorHandling/division?numerator=10&denominator=0